// Generated by PicoPixel.io — https://picopixel.io
/**
 * @file fonts.c
 * @brief Custom font lookup for LVGL UI
 *
 * IMPORTANT FOR ARDUINO:
 * Do not #include multiple LVGL font .c files in this file. Each exported
 * font file contains internal static symbols with common names such as
 * glyph_bitmap, glyph_dsc, cmaps, and font_dsc. Including several font .c
 * files into one translation unit causes redefinition errors.
 *
 * The three font implementation files are included by small wrapper .c files
 * in the sketch root so Arduino compiles each font as its own translation unit:
 *   - font_14px_compile.c
 *   - font_32px_compile.c
 *   - font_22px_compile.c
 */

#include "fonts/fonts.h"
#include <string.h>

const lv_font_t* ui_get_font_by_name(const char* name) {
    if (name == NULL) return NULL;
    if (strcmp(name, "font_1f80282278ac80f980081f6fbc62d963") == 0) return &font_1f80282278ac80f980081f6fbc62d963;
    if (strcmp(name, "font_1f80282278ac80f980081f763c890284") == 0) return &font_1f80282278ac80f980081f763c890284;
    if (strcmp(name, "font_1f80282278ac80f980081f765a57f7d7") == 0) return &font_1f80282278ac80f980081f765a57f7d7;
    return NULL;
}
