// Generated by PicoPixel.io — https://picopixel.io
#include "images.h"

#include "images/pngwing_com.c"
#include "images/drone.c"
const ext_img_desc_t images[2] = {
    { "pngwing_com", &pngwing_com },
    { "drone", &drone }
};
