// Generated by PicoPixel.io — https://picopixel.io
#ifndef PICOPIXEL_LVGL_UI_SCREENS_H
#define PICOPIXEL_LVGL_UI_SCREENS_H

#include <lvgl.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _objects_t {
    lv_obj_t *screen_1;
    lv_obj_t *roll;
    lv_obj_t *image_2;
    lv_obj_t *rx_bar;
    lv_obj_t *pitch;
    lv_obj_t *pitch_1;
    lv_obj_t *container_1;
    lv_obj_t *label_1;
    lv_obj_t *roll_1;
    lv_obj_t *label_menu1;
    lv_obj_t *label_3;
    lv_obj_t *tx;
    lv_obj_t *throttle;
    lv_obj_t *image_1;
    lv_obj_t *alt;
    lv_obj_t *rx;
    lv_obj_t *screen;
    lv_obj_t *top_label;
    lv_obj_t *spinbox_1;
    lv_obj_t *telem;
    lv_obj_t *label_2;
    lv_obj_t *yaw;
    lv_obj_t *dbm;
    lv_obj_t *terminal;
    lv_obj_t *tx_bar;
    lv_obj_t *container_2;
} objects_t;

extern objects_t objects;

enum ScreensEnum {
    SCREEN_ID_SCREEN_1 = 1,
};

void create_screen_screen_1();
void tick_screen_screen_1();
void delete_screen_screen_1();

void tick_screen_by_id(enum ScreensEnum screenId);
void tick_screen(int screen_index);

void delete_screen_by_id(enum ScreensEnum screenId);

void create_screens();


#ifdef __cplusplus
}
#endif

#endif /*PICOPIXEL_LVGL_UI_SCREENS_H*/
